spring:
  application:
    name: onified-metadata-service

  datasource:
    jdbc-url: jdbc:postgresql://localhost:5432/onified_metadata_db
    username: postgres
    password: Srinu19#
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080
  servlet:
    context-path: /metadata-service

logging:
  level:
    com.onified.platform.metadata: DEBUG
