server:
  port: 9080

spring:
  application:
    name: onified-gateway
  cloud:
    compatibility-verifier:
      enabled: false
    gateway:
      discovery:
        locator:
          enabled: false
      routes:
        # Platform Management Service
        - id: platform-management-service
          uri: http://platform-management-service:9081
          predicates:
            - Path=/platform-management/**
          filters:
            - StripPrefix=1
            - name: CircuitBreaker
              args:
                name: platform-management-circuit-breaker
                fallbackUri: forward:/fallback/platform-management

        # Authentication Service
        - id: authentication-service
          uri: http://authentication-service:9083
          predicates:
            - Path=/api/auth/**
      
# Eureka Client Configuration (Disabled for now)
eureka:
  client:
    enabled: ${EUREKA_ENABLED:false}
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://eureka-server:8761/eureka/}
    register-with-eureka: ${EUREKA_ENABLED:false}
    fetch-registry: ${EUREKA_ENABLED:false}
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

# Circuit Breaker Configuration
resilience4j:
  circuitbreaker:
    instances:
      platform-management-circuit-breaker:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10000

# Logging Configuration
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    com.onified.gateway: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n" 