server:
  port: 9080

spring:
  application:
    name: onified-gateway
  cloud:
    compatibility-verifier:
      enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        # Application Config Service
        - id: app-config-service
          uri: lb://application-config-service
          predicates:
            - Path=/appConfig/**
          filters:
            - StripPrefix=1
            - name: CircuitBreaker
              args:
                name: app-config-circuit-breaker
                fallbackUri: forward:/fallback/app-config
        
        # Authentication Service
        - id: auth-service
          uri: lb://authentication-service
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
            - name: CircuitBreaker
              args:
                name: auth-circuit-breaker
                fallbackUri: forward:/fallback/auth
        
        # User Management Service
        - id: ums-service
          uri: lb://user-management-service
          predicates:
            - Path=/ums/**
          filters:
            - StripPrefix=1
            - name: CircuitBreaker
              args:
                name: ums-circuit-breaker
                fallbackUri: forward:/fallback/ums
        
        # Permission Registry Service
        - id: permission-service
          uri: lb://permission-registry-service
          predicates:
            - Path=/permissions/**
          filters:
            - StripPrefix=1
            - name: CircuitBreaker
              args:
                name: permission-circuit-breaker
                fallbackUri: forward:/fallback/permissions
      
      # Global CORS configuration
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true

# Eureka Client Configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    health:
      show-details: always

# Circuit Breaker Configuration
resilience4j:
  circuitbreaker:
    instances:
      app-config-circuit-breaker:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10000
      auth-circuit-breaker:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10000
      ums-circuit-breaker:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10000
      permission-circuit-breaker:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10000

# Logging Configuration
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    com.onified.gateway: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n" 