server:
  port: 9080

spring:
  application:
    name: onified-gateway
  cloud:
    compatibility-verifier:
      enabled: false
    gateway:
      discovery:
        locator:
          enabled: false
      routes:
        # Platform Management Service
        - id: platform-management-service
          uri: http://platform-management-service:9081
          predicates:
            - Path=/api/platform/**
          filters:
            - StripPrefix=1
            - name: CircuitBreaker
              args:
                name: platform-management-circuit-breaker
                fallbackUri: forward:/fallback/platform

        # Authentication Service
        - id: authentication-service
          uri: http://authentication-service:9083
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1
            - name: CircuitBreaker
              args:
                name: authentication-circuit-breaker
                fallbackUri: forward:/fallback/auth
      
# Eureka Client Configuration (Disabled for now)
eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
    health-check-url-path: /actuator/health
    instance-id: ${spring.application.name}:${server.port}
  client:
    enabled: ${EUREKA_ENABLED:true}
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
    register-with-eureka: ${EUREKA_ENABLED:true}
    fetch-registry: ${EUREKA_ENABLED:true}

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

# Circuit Breaker Configuration
resilience4j:
  circuitbreaker:
    instances:
      platform-management-circuit-breaker:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10000

# Logging Configuration
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    com.onified.gateway: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
  file:
    name: ${LOG_DIR:-/app/logs}/onified-gateway.log 