version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-onified}
      POSTGRES_USER: ${POSTGRES_USER:-onified}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-onified}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # Keycloak Database
  keycloak-db:
    image: postgres:15
    container_name: keycloak-db
    environment:
      POSTGRES_DB: ${KEYCLOAK_DB_NAME:-keycloak}
      POSTGRES_USER: ${KEYCLOAK_DB_USER:-keycloak}
      POSTGRES_PASSWORD: ${KEYCLOAK_DB_PASSWORD:-keycloak}
    ports:
      - "5433:5432"
    volumes:
      - keycloak_data:/var/lib/postgresql/data

  # Keycloak Identity Provider
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.2
    container_name: keycloak
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/${KEYCLOAK_DB_NAME:-keycloak}
      KC_DB_USERNAME: ${KEYCLOAK_DB_USER:-keycloak}
      KC_DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD:-keycloak}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN:-admin}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD:-admin123}
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HTTP_ENABLED: true
    ports:
      - "9090:8080"
    depends_on:
      - keycloak-db
    command: start-dev

  # Eureka Server (temporarily disabled)
  # eureka-server:
  #   build: ./eureka-server
  #   container_name: eureka-server
  #   ports:
  #     - "8761:8761"
  #   environment:
  #     - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
  #     - EUREKA_INSTANCE_HOSTNAME=eureka-server

  onified-gateway:
    build: ./onified-gateway
    container_name: onified-gateway
    ports:
      - "9080:9080"
    environment:
      LOG_DIR: ${GATEWAY_LOG_DIR:-/app/logs}
    volumes:
      - ${GATEWAY_LOG_DIR:-./logs/gateway}:/app/logs
    # environment:
    #   - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    #   - EUREKA_INSTANCE_HOSTNAME=onified-gateway
    # depends_on:
    #   - eureka-server

  application-config-service:
    build: ./application-config-service
    container_name: application-config-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB:-onified}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER:-onified}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD:-onified}
      LOG_DIR: ${APP_CONFIG_LOG_DIR:-/app/logs}
      # EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      # EUREKA_INSTANCE_HOSTNAME: application-config-service
    ports:
      - "9082:9082"
    volumes:
      - ${APP_CONFIG_LOG_DIR:-./logs/app-config}:/app/logs
    depends_on:
      - postgres
      # - eureka-server

  authentication-service:
    build: ./authentication-service
    container_name: authentication-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB:-onified}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER:-onified}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD:-onified}
      LOG_DIR: ${AUTH_LOG_DIR:-/app/logs}
      # EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      # EUREKA_INSTANCE_HOSTNAME: authentication-service
      # Keycloak Configuration
      KEYCLOAK_AUTH_SERVER_URL: http://keycloak:8080
      KEYCLOAK_REALM: ${KEYCLOAK_REALM:-onified}
      KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID:-onified-auth-service}
      KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET:-your-client-secret}
    ports:
      - "9081:9081"
    volumes:
      - ${AUTH_LOG_DIR:-./logs/auth-service}:/app/logs
    depends_on:
      - postgres
      - keycloak
      # - eureka-server

  permission-registry-service:
    build: ./permission-registry-service
    container_name: permission-registry-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB:-onified}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER:-onified}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD:-onified}
      LOG_DIR: ${PERMISSION_LOG_DIR:-/app/logs}
      # EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      # EUREKA_INSTANCE_HOSTNAME: permission-registry-service
    ports:
      - "9084:9084"
    volumes:
      - ${PERMISSION_LOG_DIR:-./logs/permission-service}:/app/logs
    depends_on:
      - postgres
      # - eureka-server

  user-management-service:
    build: ./user-management-service
    container_name: user-management-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB:-onified}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER:-onified}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD:-onified}
      LOG_DIR: ${USER_MGMT_LOG_DIR:-/app/logs}
      # EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      # EUREKA_INSTANCE_HOSTNAME: user-management-service
    ports:
      - "9083:9083"
    volumes:
      - ${USER_MGMT_LOG_DIR:-./logs/user-management}:/app/logs
    depends_on:
      - postgres
      # - eureka-server

  # Angular Frontend
  onified-frontend:
    build: ./web
    container_name: onified-frontend
    ports:
      - "4200:80"
    environment:
      NODE_ENV: production
      LOG_DIR: ${FRONTEND_LOG_DIR:-/app/logs}
    volumes:
      - ${FRONTEND_LOG_DIR:-./logs/frontend}:/app/logs
    depends_on:
      - onified-gateway
      - keycloak
    restart: unless-stopped

volumes:
  pgdata:
  keycloak_data: 