apiVersion: apps/v1
kind: Deployment
metadata:
  name: onified-frontend
  namespace: onified
spec:
  replicas: 2
  selector:
    matchLabels:
      app: onified-frontend
  template:
    metadata:
      labels:
        app: onified-frontend
    spec:
      containers:
      - name: onified-frontend
        image: onified/frontend:latest
        ports:
        - containerPort: 80
        env:
        - name: NODE_ENV
          value: "production"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10 