# Use PERMISSION_REGISTRY_PORT from environment, default to 9084
server:
  port: ${PERMISSION_REGISTRY_PORT:9084}

spring:
  config:
    import: optional:.env[.properties]
  application:
    name: permission-registry-service
  datasource:
    url: ${PERMISSION_DB_URL:jdbc:postgresql://localhost:5432/permission_registry_db}
    username: ${PERMISSION_DB_USERNAME:postgres}
    password: ${PERMISSION_DB_PASSWORD:root}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    open-in-view: false

logging:
  level:
    root: INFO
    org.springframework: INFO
    org.springframework.web: DEBUG
    org.springframework.jdbc.core: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.onified.permission: DEBUG
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
  file:
    name: ${LOG_DIR:-/app/logs}/permission-registry-service.log

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

# Feign client config for application-config-service:
# - If APPLICATION_CONFIG_URL is set, it is used.
# - Otherwise, http://localhost:9082 is used (local dev by default).
# - For Docker Compose, set APPLICATION_CONFIG_URL to http://application-config-service:9082 in your .env.
feign:
  client:
    config:
      application-config-service:
        url: ${APPLICATION_CONFIG_URL:http://localhost:9082}

# Eureka Client Configuration
eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
    health-check-url-path: /actuator/health
  client:
    enabled: ${EUREKA_ENABLED:true}
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
    register-with-eureka: ${EUREKA_ENABLED:true}
    fetch-registry: ${EUREKA_ENABLED:true}