spring:
  config:
    import: optional:.env[.properties]
  application:
    name: authentication-service
  datasource:
    url: ${AUTH_DB_URL:jdbc:postgresql://localhost:5432/authentication_db}
    username: ${AUTH_DB_USERNAME:postgres}
    password: ${AUTH_DB_PASSWORD:root}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    open-in-view: false
  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: true
    locations: classpath:db/migration
    table: flyway_schema_history
    baseline-version: 0
    baseline-description: Initial baseline
  cloud:
    compatibility-verifier:
      enabled: false

server:
  port: 9081

jwt:
  secret: yourVerySecretKeyForJWTTokenGenerationThatShouldBeLongAndComplex12345!@#$%^&*() # !! IMPORTANT: Change this in production !!
  expiration: 3600000 # 1 hour in milliseconds (adjust as needed)

feign:
  client:
    config:
      user-management-service:
        url: http://localhost:9083 # URL of your User Management Service

logging:
  level:
    com.onified.ai.authentication_service: DEBUG
    org.springframework.security: DEBUG
    org.keycloak: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
  file:
    name: ${LOG_DIR:-/app/logs}/authentication-service.log
    max-size: 10MB
    max-history: 30
    total-size-cap: 1GB

# OAuth2 Configuration (temporarily disabled for testing)
# security:
#   oauth2:
#     resourceserver:
#       jwt:
#         issuer-uri: ${KEYCLOAK_AUTH_SERVER_URL:http://localhost:9090}/realms/${KEYCLOAK_REALM:onified}
#     client:
#       registration:
#         keycloak:
#           client-id: ${KEYCLOAK_CLIENT_ID:onified-auth-service}
#           client-secret: ${KEYCLOAK_CLIENT_SECRET:your-client-secret}

# Keycloak Configuration
keycloak:
  auth-server-url: ${KEYCLOAK_AUTH_SERVER_URL:http://localhost:9090}
  realm: ${KEYCLOAK_REALM:onified}
  client-id: ${KEYCLOAK_CLIENT_ID:onified-auth-service}
  client-secret: ${KEYCLOAK_CLIENT_SECRET:your-client-secret}
  admin:
    username: admin
    password: admin123
    realm: master

# Eureka Client Configuration (disabled since Eureka server is not running)
eureka:
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always