spring:
  datasource:
    url: ${TENANT_MGMT_DB_URL:jdbc:postgresql://localhost:5432/tenant_management_db}
    username: ${TENANT_MGMT_DB_USERNAME:postgres}
    password: ${TENANT_MGMT_DB_PASSWORD:root}
    driver-class-name: org.postgresql.Driver
  application:
    name: tenant-management-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    open-in-view: false

server:
  port: ${TENANT_MGMT_PORT:9086}

eureka:
  client:
    enabled: ${EUREKA_ENABLED:false}
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://eureka-server:8761/eureka/}
    register-with-eureka: ${EUREKA_ENABLED:false}
    fetch-registry: ${EUREKA_ENABLED:false}
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always 