spring:
  datasource:
    url: ${TENANT_MGMT_DB_URL:jdbc:postgresql://localhost:5432/tenant_management_db}
    username: ${TENANT_MGMT_DB_USERNAME:postgres}
    password: ${TENANT_MGMT_DB_PASSWORD:root}
    driver-class-name: org.postgresql.Driver
  application:
    name: tenant-management-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    open-in-view: false

server:
  port: ${TENANT_MGMT_PORT:9086}

eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
    health-check-url-path: /actuator/health
  client:
    enabled: ${EUREKA_ENABLED:true}
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
    register-with-eureka: ${EUREKA_ENABLED:true}
    fetch-registry: ${EUREKA_ENABLED:true}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  file:
    name: ${LOG_DIR:-/app/logs}/tenant-management-service.log 