apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: onified
data:
  POSTGRES_DB: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: root
  PGDATA: /var/lib/postgresql/data/pgdata 