apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-script
  namespace: onified
data:
  init.sql: |
    -- Create databases for each service
    CREATE DATABASE platform_mgmt_db;
    CREATE DATABASE tenant_management_db;
    CREATE DATABASE user_management_db;
    CREATE DATABASE permission_registry_db;
    CREATE DATABASE application_config_db;
    CREATE DATABASE authentication_db;
    CREATE DATABASE keycloak_db;
    
    -- Grant permissions
    GRANT ALL PRIVILEGES ON DATABASE platform_mgmt_db TO postgres;
    GRANT ALL PRIVILEGES ON DATABASE tenant_management_db TO postgres;
    GRANT ALL PRIVILEGES ON DATABASE user_management_db TO postgres;
    GRANT ALL PRIVILEGES ON DATABASE permission_registry_db TO postgres;
    GRANT ALL PRIVILEGES ON DATABASE application_config_db TO postgres;
    GRANT ALL PRIVILEGES ON DATABASE authentication_db TO postgres;
    GRANT ALL PRIVILEGES ON DATABASE keycloak_db TO postgres; 