server:
  port: 9081

spring:
  config:
    import: optional:.env[.properties]
  application:
    name: application-config-service
  datasource:
    url: ${APP_CONFIG_DB_URL}
    username: ${APP_CONFIG_DB_USERNAME}
    password: ${APP_CONFIG_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    root: INFO
    org.springframework: INFO
    org.springframework.web: DEBUG
    org.springframework.jdbc.core: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.onified.appconfig: DEBUG
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
